### ISSUE TITLE
Not an issue, but a request

### ISSUE THREAD

**Issue by dd-ctss** [SOUMEE2000/Resume_Scanner#2]
Hi, I'm interested in using your excellent ATS code within a website I would like to put live to help both job seekers and employers to analyse CVs and resumes. 

I will provide a link from the site, back to this Github profile, to give you the credit, which is well deserved. 

Can you confirm if I am able to do this please? thanks

**Comment by SOUMEE2000** [comment]
Hello. 
Thank you so much for your interest. 
Of course you may use the code. It's open source. Please do give the repo a star if it helped you. 

Thank you.
